version: '3.9'
services:
  brave:
    build: .
    container_name: brave_docker
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/romulo/.Xauthority
    command: ["bash", "-c", "while sleep 1000; do :; done"]
    working_dir: /home/romulo
    network_mode: "host"
    restart: always
networks:
  default:
   external:
     name: host